#include "src/main.c"
#include "src/uitheme.c"

#include "../../src/uifont.c"
#include "../../src/ui.c"
#include "../../src/uidrawlist.c"
#include "../../src/uirender.c"
#include "../../src/uivisual.c"

#include "../../../taasdk/src/gl.c"
#include "../../../taasdk/src/glcontext.c"
#include "../../../taasdk/src/keyboard.c"
#include "../../../taasdk/src/log.c"
#include "../../../taasdk/src/mouse.c"
#include "../../../taasdk/src/system.c"
#include "../../../taasdk/src/window.c"
